export const HONEYPOT_URLS = [
  { url: "contact/", name: "Contact" },
  { url: "api/contact/", name: "Contact" },
  { url: "contact/submit/", name: "Contact Submit" },
  "submit-form/",
  { url: "api/message/", name: "Message" },
  { url: "send-message/", name: "Send Message" },
  "company/",
  { url: "feedback/", name: "Feedback" },
  { url: "support-ticket/", name: "Support Ticket" },
  { url: "api/v1/comments/", name: "Comments" },
  { url: "api/v1/reviews/", name: "Reviews" },
  "api/v1/profile/update/",
  { url: "submit-feedback/", name: "Submit Feedback" },
  "post/create/",
  { url: "upload/", name: "Upload" },
  { url: "upload/image/", name: "Upload Image" },
  "phpinfo.php",
  { url: "adminer.php", name: "Adminer" },
  { url: "debug.php", name: "Debug" },
  "login.php",
  { url: "dashboard.php", name: "Dashboard" },
  "api/admin/",
  { url: "api/v1/admin/login/", name: "Admin Login" },
  "api/v1/user/create/",
  { url: "api/v1/user/update/", name: "User Update" },
  { url: "api/v1/messages/", name: "Messages" },
  { url: "api/v1/submit/", name: "Submit" },
  ".git/",
  { url: "backup/", name: "Backup" },
  { url: "old/", name: "Old" },
  { url: "test/", name: "Test" },
  { url: "dev/", name: "Dev" },
  { url: "admin-login/", name: "Admin Login" },
  { url: "cp/", name: "Control Panel" },
  { url: "dashboard/login/", name: "Dashboard Login" },
  { url: "adminpanel/", name: "Adminpanel" },
  "search/",
  { url: "api/search/", name: "API Search" },
  { url: "query/", name: "Query" },
  { url: "lookup/", name: "Lookup" },
  { url: "filter/", name: "Filter" },
];
